### ISSUE TITLE
target_type = 'landmarks' error

### ISSUE THREAD

**Issue by luckynote** [face-alignment-group-of-ahucs/SHN-based-2D-face-alignment#2]
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main(config)
  File "main.py", line 47, in main
    solver.train()
  File "/media/luckynote/Tool/face-recognition-dl/SHN-based-2D-face-alignment/solver.py", line 149, in train
    loss = self.critertion(out,targets)
  File "/home/luckynote/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/luckynote/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 443, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/luckynote/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 2256, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/luckynote/anaconda3/lib/python3.6/site-packages/torch/functional.py", line 62, in broadcast_tensors
    return torch._C._VariableFunctions.broadcast_tensors(tensors)
RuntimeError: The size of tensor a (128) must match the size of tensor b (2) at non-singleton dimension 3

**Comment by 738654805** [comment]
@luckynote you should match the size of output of the network and the target.
